FROM elixir:1.7
COPY ./src-ex /src
COPY ./files/accounts1.2m.txt /accounts1.2m.txt
COPY ./files/transactions10m.txt /transactions10m.txt
WORKDIR /src

ENV MIX_ENV=prod
RUN mix local.hex --force \
&& mix deps.get \
&& mix release
